name: Delete older workflows runs

on:
  workflow_dispatch:

permissions: 
  contents: read
  id-token: write

jobs:
  delete-old-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.CICD_TOKEN_FOR_TF_MODULES }}
          days-ago: 0
          #keep-latest: 10
          #dry-run: true
   - "name": "who has forked me?"
     "run": |
       echo "who has forked me? ..."
       curl -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.CICD_TOKEN_FOR_TF_MODULES }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/SAP-samples/teched2025-XP264/forks